# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "feature" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo is java here
          java --version
          echo is java here
          git --version
 
